export default {
  img: require('../assets/images/blueTick.png'),
  email: require('../assets/images/email.png'),
  lock: require('../assets/images/lock.png'),
  arrow_left:require('../assets/images/arrow_left.png'),
  loader:require('../assets/images/Loader.png'),
  home:require('../assets/images/home.png'),
  home_color:require('../assets/images/home-color.png'),
  schdule:require('../assets/images/schdule.png'),
  schdule_color:require('../assets/images/schdule-color.png'),
  pres:require('../assets/images/pres.png'),
  pres_color:require('../assets/images/pres-color.png'),
  getphar:require('../assets/images/getphar.png'),
  getphar_color:require('../assets/images/getphar-color.png'),
  menu:require('../assets/images/menuicon.png'),
    health:require('../assets/images/health-prev.png'),
  mic:require('../assets/images/mic.png'),
  question:require('../assets/images/question.png'),
  remainder:require('../assets/images/remainder.png'),
  medical_services:require('../assets/images/medical-service.png'),
  offer:require('../assets/images/offer.png'),
  calendar:require('../assets/images/calendar.png'),
  message:require('../assets/images/messages.png'),
  location:require('../assets/images/location.png'),
  pathlab:require('../assets/images/pathlab.png'),
  phar24:require('../assets/images/phar24.png'),
  star:require('../assets/images/star.png'),
  upload:require('../assets/images/upload.png'),
  upload_arrow:require('../assets/images/upload-arrow.png'),
  
};

 
