export default {
   Login:'Login',
   Healthcare:'Healthcare',
   donhave:'Don’t Have an Account : ',
   register:'Click here to register',
   email:'Email Id',
   password:'Password',
   LOGIN:'LOGIN',
   Questions:'Questions',
   Reminders:"Reminders",
   Messages:'Messages',
   Calendar:'Calendar',
   upload_prescription:'UPLOAD PRESCRIPTION',
   upload_des:'Upload a Prescription and Tell Us What you Need. We do the Rest. !',
   offer:'Flat 25% OFF ON MEDICINES',
   order_now:'Order Now',
   logout:'Logout',
   are_you: "Are you sure you want to log out?",
   cancel:'Cancel',
   yes:'Yes',
   forgot:'Forgot Password !',
   upload_pres:'Upload a Prescription and Tell Us What you Need. We do the Rest. !',
   Mohali:'Mohali',
   pharnear:'Pharmacy Nearby',
   we_will:'We will show the pharmacy that fits as per your prescription.',
   uploadlink:'Upload Link',
   uploadfile:"Upload File",
   continue:"Continue",
   
};
